### ISSUE TITLE
Compatibility with PHP 5.3

### ISSUE THREAD

**Issue by fabpot** [schmittjoh/php-manipulator#1]
The `composer.json` claims compatibility with PHP 5.3, but the code is not. In `SimultaneousTokenAstStream` for instance, there is a reference to `T_TRAIT`, which is only available in PHP 5.4+.

**Comment by schmittjoh** [comment]
Actually, it was not explicitly marked as compatible, but it should be easy to keep.

I've just pushed a fix for the T_TRAIT constant. Hopefully, there will be nothing else.
