### ISSUE TITLE
Missing token removal methods?

### ISSUE THREAD

**Issue by jfsimon** [schmittjoh/php-manipulator#4]
Hi Johannes,

I may be wrong, but token streams are mutable since they provide methods for token insertion. My problem is that I can't find any method for token removal. Is there a reason for that?

I could send a PR to implement such methods, but I prefer to ask if it's a good idea before. I'd like to have two new methods in the `TokensStream` class:
- `removeToken(AbstractToken $token)`
- `removeConsecutiveTokens(AbstractToken $firstToken, AbstractToken $lastToken)`

Tell me what you think!

**Comment by schmittjoh** [comment]
In practice, it was often easier to create a new stream by iterating over the existing one like this:

``` php
$newContent = '';
while ($stream->moveNext()) {
    if ($someCondition) {
        continue; // skip some tokens (effectively removing them from the stream)
    }

    $newContent .= $stream->token->getContent();
}
```

If you like to re-iterate over the stream, then you can set the new content and start all over:

``` php
$stream->setCode($newContent);
// Do your work on the updated stream.
```

I think adding more methods for mutating a stream is going to be hard to maintain in the future. Instead, maybe we can add a utility class which simplifies the above process, but I'd like to gather a few use-cases first. Maybe you could elaborate what you're trying to do?

**Comment by jfsimon** [comment]
Thanks for your code snippet, this is indeed more simple than adding a (maybe hard to code) removal method!
I'll apply it and send you the repo link as a use-case (nothing has been pushed yet).
Tahnks for this great lib!
